# Generated by Django 4.1.5 on 2023-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
