# Generated by Django 4.1.5 on 2023-04-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
