# Generated by Django 4.1.5 on 2023-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_post_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
