# Generated by Django 4.1.5 on 2023-04-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/images/{category}/{id}/'),
        ),
    ]
