# Generated by Django 4.1.5 on 2023-04-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
