# Generated by Django 4.1.5 on 2023-04-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_remove_post_description_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
